"""Bake runtime-generated GLSL into .qsb (Qt 6's ShaderEffect / custom materials only take .qsb).

Why it must be baked at runtime: the shader carries the user-entered expression (generated by
sympy), while Qt's official workflow bakes with qsb at build time and ships the .qsb as a
resource — impossible here. The baked result is cached in a temp directory keyed by the source
sha256, so only the first use of an expression pays for the bake and the frame loop makes no
calls at all.

Cross-platform: on Windows the wheel ships ``PySide6/qsb.exe``; PySide6's packaging script has no
platform condition for it, so all three platforms are expected to have it, but only Windows has
been confirmed. If it is not found we fall back to PATH, and otherwise raise with the ways to
obtain it.
"""

from __future__ import annotations

import hashlib
import os
import shutil
import subprocess
import tempfile
from pathlib import Path

__all__ = ["bake", "qsb_binary"]

_EXE = "qsb.exe" if os.name == "nt" else "qsb"


def _candidates() -> list[Path]:
    """Places qsb may live: the PySide6 package directory (layout differs per platform), Qt's
    libexec, and PATH."""
    cands: list[Path] = []
    try:
        import PySide6  # lazy import: only the QML front-end needs to bake shaders

        pkg = Path(PySide6.__file__).parent
        cands += [pkg / _EXE, pkg / "Qt" / "bin" / _EXE, pkg / "Qt" / "libexec" / _EXE]
    except ImportError:  # without PySide6, a qsb on PATH is still allowed
        pass
    found = shutil.which("qsb")
    if found:
        cands.append(Path(found))
    return cands


def qsb_binary() -> Path:
    """Locate qsb (the Qt Shader Baker)."""
    for cand in _candidates():
        if cand.exists():
            return cand
    raise RuntimeError(
        "cannot find qsb (Qt Shader Baker); the QML front-end cannot bake its shaders. "
        "Three ways to get it:\n"
        "  1) use the PySide6 wheel (ships qsb.exe on Windows; check other platforms first)\n"
        "  2) install Qt Shader Tools: a distribution package (e.g. qt6-shadertools) or the "
        "Qt online installer\n"
        "  3) if you already have qsb, put it on PATH\n"
        "see https://doc.qt.io/qt-6/qtshadertools-index.html"
    )


def bake(source: str, stage: str, cache_dir: Path | str | None = None) -> Path:
    """Bake one GLSL source into .qsb and return the file path (cached by source hash).

    stage: "vert" or "frag"
    """
    if stage not in ("vert", "frag"):
        raise ValueError(f"stage must be 'vert' or 'frag', got {stage!r}")

    # v2: the source file must use a .vert/.frag suffix — qsb detects the stage from the
    #     suffix, so a .glsl file is treated as a vertex shader. The version goes into the
    #     hash, which invalidates old cache entries.
    key = hashlib.sha256(f"v2\0{stage}\0{source}".encode()).hexdigest()[:16]
    out_dir = Path(cache_dir) if cache_dir else Path(tempfile.gettempdir()) / "qmlmathplot-qsb"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"{stage}-{key}.qsb"
    if out_path.exists():
        return out_path

    src_path = out_dir / f"{stage}-{key}.{stage}"
    src_path.write_text(source, encoding="utf-8")
    tmp_out = out_path.with_suffix(".qsb.tmp")
    # --qt6 == --glsl "100 es,120,150" --hlsl 50 --msl 12, the standard target set for Qt Quick
    # materials
    proc = subprocess.run(  # noqa: S603
        [str(qsb_binary()), "--qt6", "-o", str(tmp_out), str(src_path)],
        capture_output=True,
        text=True,
        check=False,
    )
    if proc.returncode != 0 or not tmp_out.exists():
        raise RuntimeError(
            f"qsb bake failed ({stage}, rc={proc.returncode}):\n{proc.stdout}\n{proc.stderr}"
        )
    tmp_out.replace(out_path)  # atomic replace: no half-written file on interrupt/concurrency
    return out_path
